### ISSUE TITLE
Keypair.json

### ISSUE THREAD

**Issue by tokayseo** [gladiusio/gladius-node-client#1]
I am getting the following after going to localhost:3000

Failed to compile
./src/components/Form.js
Module not found: Can't resolve '../keypair.json' in '/usr/app/src/components'

**Comment by code-merc** [comment]
Currently a bug I'm working on fixing, in the mean time enter the container and run the command "node setup.js"

**Comment by arnoldvilleneuve** [comment]
how do you "enter the container" and run "node setup.js" exactly.

**Comment by ghunti** [comment]
@arnoldvilleneuve If you are still looking for it:
```
docker exec -ti gladiusnodeclient_web_1 /bin/bash
node setup.js
```
