### ISSUE TITLE
Module not found: Can't resolve '../keypair.json' in '/usr/app/src/components'

### ISSUE THREAD

**Issue by sebastianhutter** [gladiusio/gladius-node-client#4]
When running the node client I receive the following error in the containers logs and also on the webinterface when trying to access localhost:3000

```
Starting the development server...

Failed to compile.

./src/components/Form.js
Module not found: Can't resolve '../keypair.json' in '/usr/app/src/components'
```

**Comment by sebastianhutter** [comment]
I am a total node.js beginner (never worked with node.js) but to me it looks like the setup.js file is somehow not executed during start of the container. Which means the keypair needed by the form component is never generated.

https://github.com/gladiusio/gladius-node-client/blob/master/app/setup.js

**Comment by sebastianhutter** [comment]
The problem is in the docker-compose file.

During the image build the Dockerfile creates the keypair.json but the docker-compose overwrites the app directory with the hosts app dir where we do not have a keypair.json

https://github.com/gladiusio/gladius-node-client/blob/master/docker-compose.yml#L16

Either remove the host volume mount or execute `npm run setup` during container start

**Comment by kevinnguyeneng** [comment]
Thanks , i do the same by remove keypair but meet another issue about web3 or metamask 
when using chrome to load localhost:3000

**Comment by sebastianhutter** [comment]
can you post the error message or a more detailed description of the issue ? I think the best approach is that you create a new issue and we discuss the details there :-)

**Comment by causehacker** [comment]
I got the same error on a fresh install, nothing in the build logs. is there a way to build this with debug output that would help? @sebastianhutter

**Comment by sebastianhutter** [comment]
@noinput the build works flawlessly ;-) the issue is how the docker container is spun up afterwards. the docker-compose file would need fixing.

the docker-compose file seems to have been written with local development in mind.

the process is the following:

1. the image gets build - during the build, the keypair.json is generated and stored in the image (<image>/app/src/keypair.json)

2. a container is created from the image and uses the hosts app directory to overwrite the images app directory via a bind mount (https://github.com/gladiusio/gladius-node-client/blob/master/docker-compose.yml#L16)

3. the application fails because there is no keypair.json available.


for a quick test, the easiest approach is to remove the bind mount from the docker-compose file (delete line 16) and run the docker-compose command again.

**Comment by ditrone** [comment]
@sebastianhutter 

That resolved my issue, thanks!
