### ISSUE TITLE
Step 4

### ISSUE THREAD

**Issue by SomeBadCoding** [gladiusio/gladius-node-client#5]
~/Gladius/gladius-node-client# docker-compose up -d --build
Building web
Step 1/6 : FROM node:boron
 ---> e8c6ec267732
Step 2/6 : WORKDIR /usr/app
 ---> Using cache
 ---> 5adb4e28a140
Step 3/6 : COPY package.json .
 ---> Using cache
 ---> 3fb7711e8e76
Step 4/6 : RUN npm install --quiet
 ---> Running in d664d3544f30
Killed
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install --quiet' returned a non-zero code: 137

**Comment by AssessOne** [comment]
I am not sure of your server resources, but I suggest increasing them - RAM in particular. Node/NPM probably needs more resources to complete the build. Suggest at least 1GB RAM, x1 2.0 Ghz+ CPU.

**Comment by SomeBadCoding** [comment]
Thanks for the suggestion, I will add some more resources to the box and give it a shot. 

This worked.
