### ISSUE TITLE
No info on "Get pool information"

### ISSUE THREAD

**Issue by Mortenest** [gladiusio/gladius-node-client#6]
I want to try this out, but I can't find any information of how to connect to any pool (where I guess the "pool information" is an IP address).

Where can I find any information on the pools?

**Comment by vKnmnn** [comment]
+1
would like to participate

**Comment by MikooDev** [comment]
+1
i also have this problem

**Comment by kleoken** [comment]
Currently there is no publicly available pool information. You could create your own pool but most likely there will be public pools by March.

**Comment by wokrucinski** [comment]
How to create my own pool? Is it necessary to have public IP address (I mean my own IP address, not my internet provider IP address)?
